<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Updating.aspx.cs" Inherits="Program6.Updating" %>

<!DOCTYPE html>
<head>
    <title>UWP - CS3870 : First Program</title>
	<link rel="stylesheet" type="text/css" href= "StyleSheet1.css" />

    <style type="text/css">
        .auto-style1 {
            margin-left: 309px;
        }
    </style>

</head>

<body>

	<form id="form1" runat="server">

	<h1 class="CS3870Title">Web Protocols, Technologies and Applications </h1> 
	<h2 class="Name">Andre Sandoval</h2>


    <ul class="navbar">
        <li> 
            <asp:TreeView ID="TreeView3" runat="server" style="margin-left: 3px; margin-top: 0px" Width="135px">
                <Nodes>
                    <asp:TreeNode SelectAction="None" Text="Prog 6" Value="Prog 6">
                        <asp:TreeNode SelectAction="None" Text="Admin" Value="Admin">
                            <asp:TreeNode Text="Set Roles" Value="Set Roles"></asp:TreeNode>
                            <asp:TreeNode Text="Updating" Value="New Node"></asp:TreeNode>
                        </asp:TreeNode>
                        <asp:TreeNode SelectAction="None" Text="Member" Value="Member">
                            <asp:TreeNode Text="Shopping" Value="New Node"></asp:TreeNode>
                            <asp:TreeNode Text="Checkout" Value="New Node"></asp:TreeNode>
                        </asp:TreeNode>
                    </asp:TreeNode>
                </Nodes>
            </asp:TreeView>
            <asp:SiteMapDataSource ID="SiteMapDataSource1" runat="server" />
&nbsp;</li>

        <li> 
            <asp:TreeView ID="TreeView2" runat="server" DataSourceID="SiteMapDataSource2" Width="141px">
            </asp:TreeView>
            <asp:SiteMapDataSource ID="SiteMapDataSource2" runat="server" />
        </li>

    </ul>
	
    <h3 style="text-align: center; display: block">
        <span style="float: left; display: inline-block; ">
            <span id="ContentPlaceHolder1_LoginName1">sandovala</span>
        </span>
          Prog 7
          <span style="float: right; display: inline-block; ">
            <a id="ContentPlaceHolder1_LoginStatus1" href="NewLoginPage.aspx" >Logout</a>
        </span>
    </h3>

              <br />
              <br />

    <p class="centerText">



        
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Prog4DatabaseConnectionString %>" SelectCommand="SELECT * FROM [checkout]"></asp:SqlDataSource>
        <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" style="margin-left: 326px" Width="374px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" CssClass="auto-style1" DataKeyNames="productId" DataSourceID="SqlDataSource1">
            <Fields>
                <asp:BoundField DataField="productId" HeaderText="productId" ReadOnly="True" SortExpression="productId" />
                <asp:BoundField DataField="productName" HeaderText="productName" SortExpression="productName" />
                <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
                <asp:BoundField DataField="Unit Price" HeaderText="Unit Price" SortExpression="Unit Price" />
                <asp:BoundField DataField="Cost" HeaderText="Cost" SortExpression="Cost" />
            </Fields>
            <PagerSettings FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast" NextPageText="Next" PreviousPageText="Previous" />
        </asp:DetailsView>



        
    </form>



</body>
</html>
